# Generated by Django 4.2.6 on 2023-11-22 03:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('file', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserFileShare',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('shared_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('accepted', 'Accepted'), ('rejected', 'Rejected'), ('pending', 'Pending')], default='pending', max_length=10)),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='file.file')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shared_files_as_member', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'user_file_share',
                'verbose_name_plural': 'user_file_shares',
                'db_table': 'user_file_shares',
                'unique_together': {('file', 'member')},
            },
        ),
    ]
