# Generated by Django 4.2.6 on 2023-12-25 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='is_sample',
            field=models.BooleanField(default=False),
        ),
    ]
