version: '3'

services:
  web:
    build: .
    command: bash -c "python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    container_name: k_test
    volumes:
    - '/var/lib/jenkins/workspace/k-quicksight/server/images:/workspace/images/'
    - '/var/lib/jenkins/workspace/k-quicksight/server/files:/workspace/files/'
    - '/var/lib/jenkins/workspace/k-quicksight/k_qicksight_app/:/workspace/app/'
    - '/var/lib/jenkins/workspace/k-quicksight/k-quicksight-scripts:/workspace/k-quicksight-scripts/'

    ports:
      - "8083:8000"
