# Generated by Django 4.2.6 on 2024-01-01 15:50

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_dashboard_is_sample'),
        ('sample', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SampleDashboard',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('analysis', models.ForeignKey(db_column='dashboard_uuid', on_delete=django.db.models.deletion.CASCADE, related_name='sample_dashboard', to='dashboard.dashboard', to_field='uuid')),
            ],
            options={
                'verbose_name': 'sample_dashboard',
                'verbose_name_plural': 'sample_dashboard',
                'db_table': 'sample_dashboard',
            },
        ),
    ]
