# Generated by Django 4.2.6 on 2024-01-01 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sample', '0002_sampledashboard'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sampleanalysis',
            old_name='analysis',
            new_name='analysis_uuid',
        ),
        migrations.RenameField(
            model_name='sampledashboard',
            old_name='analysis',
            new_name='dashboard_uuid',
        ),
    ]
