# Generated by Django 4.2.6 on 2024-01-01 16:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_dashboard_is_sample'),
        ('analysis', '0010_alter_analysis_recommneded'),
        ('sample', '0004_alter_sampleanalysis_analysis_uuid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sampleanalysis',
            name='analysis_uuid',
            field=models.OneToOneField(db_column='analysis_uuid', on_delete=django.db.models.deletion.CASCADE, related_name='sample_analysis', to='analysis.analysis', to_field='uuid'),
        ),
        migrations.AlterField(
            model_name='sampledashboard',
            name='dashboard_uuid',
            field=models.OneToOneField(db_column='dashboard_uuid', on_delete=django.db.models.deletion.CASCADE, related_name='sample_dashboard', to='dashboard.dashboard', to_field='uuid'),
        ),
    ]
