# Generated by Django 4.2.6 on 2024-01-01 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sample', '0005_alter_sampleanalysis_analysis_uuid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sampleanalysis',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default='2023-12-08 09:26:58.373647+07'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sampleanalysis',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sampledashboard',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default='2023-12-08'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sampledashboard',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
