# Generated by Django 4.2.6 on 2024-01-02 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sample', '0006_sampleanalysis_created_at_sampleanalysis_is_deleted_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='sampleanalysis',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('analysis_uuid', 'is_deleted'), name='unique_analysis_uuid_not_deleted'),
        ),
    ]
