# Generated by Django 4.2.6 on 2023-12-08 02:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Dashboard',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200, null=True)),
                ('thumbnail', models.CharField(max_length=200, null=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('json_data', models.JSONField(default=None)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users_dashboard', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'dashboards',
                'verbose_name_plural': 'dashboards',
                'db_table': 'dashboards',
            },
        ),
    ]
