# Generated by Django 4.2.6 on 2023-12-08 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dashboard',
            name='json_data',
            field=models.JSONField(default=None, null=True),
        ),
    ]
