# Generated by Django 4.2.6 on 2023-12-12 10:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('file', '0001_initial'),
        ('dashboard', '0002_alter_dashboard_json_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='dashboard',
            name='file',
            field=models.ForeignKey(default=5, on_delete=django.db.models.deletion.CASCADE, related_name='file_dasboard', to='file.file'),
            preserve_default=False,
        ),
    ]
