# Generated by Django 4.2.6 on 2023-12-25 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_dashboard_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='dashboard',
            name='is_sample',
            field=models.BooleanField(default=False),
        ),
    ]
