# Generated by Django 4.2.6 on 2023-12-06 11:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Analysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(choices=[('descriptive_statistic', 'Descriptive Statistic'), ('random_number_generation', 'Random Number Generation'), ('correlation', 'Correlation'), ('covariance', 'Covariance'), ('simple_linear_regression', 'Simple Linear Regression'), ('non_linear_regression', 'Non-Linear Regression'), ('multiple_linear_regression', 'Multiple Linear Regression')], max_length=30)),
                ('analysis_data', models.JSONField()),
                ('independent_variable', models.CharField(max_length=200)),
                ('dependent_variable', models.CharField(max_length=200)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users_analysis', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'analysis',
                'verbose_name_plural': 'analysis',
                'db_table': 'analysis',
            },
        ),
    ]
