# Generated by Django 4.2.6 on 2023-12-07 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0002_analysis_created_at_analysis_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysis',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
