# Generated by Django 4.2.6 on 2023-12-08 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0003_analysis_is_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysis',
            name='thumbnail',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='analysis',
            name='title',
            field=models.CharField(default='ANALYSIS', max_length=30, null=True),
        ),
    ]
