# Generated by Django 4.2.6 on 2023-12-25 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0005_analysis_filename'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysis',
            name='is_sample',
            field=models.BooleanField(default=False),
        ),
    ]
