# Generated by Django 4.2.6 on 2023-12-31 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0007_alter_analysis_dependent_variable_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysis',
            name='recommned',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
