# Generated by Django 4.2.6 on 2023-12-31 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0008_analysis_recommned'),
    ]

    operations = [
        migrations.RenameField(
            model_name='analysis',
            old_name='recommned',
            new_name='recommneded',
        ),
    ]
