# Generated by Django 4.2.6 on 2024-01-01 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0009_rename_recommned_analysis_recommneded'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analysis',
            name='recommneded',
            field=models.TextField(max_length=500, null=True),
        ),
    ]
