# Generated by Django 4.2.6 on 2023-12-14 01:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('visualization', '0002_alter_visualization_options_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Visualization',
        ),
    ]
