# Generated by Django 4.2.6 on 2023-12-22 08:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_user_password_reset_token'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='password_reset_token',
            new_name='token',
        ),
    ]
