# Generated by Django 4.2.6 on 2023-12-22 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_rename_password_reset_token_user_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='uid_base64',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
