# Generated by Django 4.2.6 on 2023-12-17 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_visualize', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagevisualize',
            name='file',
            field=models.CharField(default='hello_jessi.jpg', max_length=200),
            preserve_default=False,
        ),
    ]
